### PR TITLE
Bump LibUV to 1.42.0

### PR DESCRIPTION
**Pull request by brainstorm**
In hopes to fix issue #348 among others listed in [LibUV's changelog](https://github.com/r-lib/fs/pull/352/files#diff-cabb30179deebd2aceb5b70dc3c7ba3414973eba6cb2e0ebea65ed06d5c67d27)

/cc @alexiswl

### CODE REVIEW

**Comment by brainstorm** [comment]
The R CMD check part is a bit problematic:

```
> rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
pdflatex not found! Not building PDF manual.
✔  checking for file ‘.../DESCRIPTION’ ...
─  preparing ‘fs’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
✔  creating vignettes (19.3s)
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (416ms)
─  checking for empty or unneeded directories
   Removed empty directory ‘fs/src/libuv-1.42.0/test/fixtures’
   Removed empty directory ‘fs/src/libuv-1.42.0/test’
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘fs_1.5.0.9000.tar.gz’

── R CMD check ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─  using log directory ‘/Users/rvalls/tmp/fs/check/fs.Rcheck’
─  using R version 4.1.2 (2021-11-01)
─  using platform: aarch64-apple-darwin20.6.0 (64-bit)
─  using session charset: UTF-8
─  using options ‘--no-manual --as-cran’
✔  checking for file ‘fs/DESCRIPTION’ ...
─  this is package ‘fs’ version ‘1.5.0.9000’
─  package encoding: UTF-8
N  checking CRAN incoming feasibility (1m 14.3s)
   Maintainer: ‘Jim Hester <james.f.hester@gmail.com>’

   Version contains large components (1.5.0.9000)

   Found the following (possibly) invalid URLs:
     URL: http://fs.r-lib.org (moved to https://fs.r-lib.org/)
       From: man/fs-package.Rd
       Status: 200
       Message: OK
     URL: https://www.tidyverse.org/lifecycle/#maturing (moved to https://lifecycle.r-lib.org/articles/stages.html)
       From: man/fs-package.Rd
       Status: 200
       Message: OK
✔  checking package namespace information ...
E  checking package dependencies (544ms)
   Package suggested but not available: ‘spelling’

   The suggested packages are required for a complete check.
   Checking can be attempted without them by setting the environment
   variable _R_CHECK_FORCE_SUGGESTS_ to a false value.

   See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
   manual.

   See
     ‘/Users/rvalls/tmp/fs/check/fs.Rcheck/00check.log’
   for details.


── R CMD check results ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── fs 1.5.0.9000 ────
Duration: 1m 15.3s

❯ checking package dependencies ... ERROR
  Package suggested but not available: ‘spelling’

  The suggested packages are required for a complete check.
  Checking can be attempted without them by setting the environment
  variable _R_CHECK_FORCE_SUGGESTS_ to a false value.

  See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
  manual.

❯ checking CRAN incoming feasibility ... NOTE
  Maintainer: ‘Jim Hester <james.f.hester@gmail.com>’

  Version contains large components (1.5.0.9000)

  Found the following (possibly) invalid URLs:
    URL: http://fs.r-lib.org (moved to https://fs.r-lib.org/)
      From: man/fs-package.Rd
      Status: 200
      Message: OK
    URL: https://www.tidyverse.org/lifecycle/#maturing (moved to https://lifecycle.r-lib.org/articles/stages.html)
      From: man/fs-package.Rd
      Status: 200
      Message: OK

1 error ✖ | 0 warnings ✔ | 1 note ✖
Error: R CMD check found ERRORs
```

Then trying to install `spelling`:

```
clang++ -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/homebrew/Cellar/r/4.1.2/lib/R/lib -L/opt/homebrew/opt/gettext/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/xz/lib -L/opt/homebrew/lib -o xml2.so connection.o init.o xml2_doc.o xml2_init.o xml2_namespace.o xml2_node.o xml2_output.o xml2_schema.o xml2_url.o xml2_xpath.o -L/Users/rvalls/.mambaforge/lib -lxml2 -L/Users/rvalls/.mambaforge/lib -lz -L/Users/rvalls/.mambaforge/lib -llzma -lpthread -L/Users/rvalls/.mambaforge/lib -liconv -L/Users/rvalls/.mambaforge/lib -licui18n -licuuc -licudata -lm -L/opt/homebrew/Cellar/r/4.1.2/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
installing to /opt/homebrew/lib/R/4.1/site-library/00LOCK-xml2/00new/xml2/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
Error :  unable to load shared object '/opt/homebrew/lib/R/4.1/site-library/00LOCK-xml2/00new/xml2/libs/xml2.so':
  dlopen(/opt/homebrew/lib/R/4.1/site-library/00LOCK-xml2/00new/xml2/libs/xml2.so, 0x0006): Library not loaded: @rpath/libxml2.2.dylib
  Referenced from: /opt/homebrew/lib/R/4.1/site-library/00LOCK-xml2/00new/xml2/libs/xml2.so
  Reason: tried: '/opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libxml2.2.dylib' (no such file), '/opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libxml2.2.dylib' (no such file), '/opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libxml2.2.dylib' (no such file)
ERROR: installing Rd objects failed for package ‘xml2’
* removing ‘/opt/homebrew/lib/R/4.1/site-library/xml2’
ERROR: dependency ‘xml2’ is not available for package ‘spelling’
* removing ‘/opt/homebrew/lib/R/4.1/site-library/spelling’
```

But then `xml2` also comes with its own baggage because my particular R version (4.1.2 from Homebrew) still does not ship with `xml2` builtin shared libs?:

```
clang++ -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/homebrew/Cellar/r/4.1.2/lib/R/lib -L/opt/homebrew/opt/gettext/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/xz/lib -L/opt/homebrew/lib -o xml2.so connection.o init.o xml2_doc.o xml2_init.o xml2_namespace.o xml2_node.o xml2_output.o xml2_schema.o xml2_url.o xml2_xpath.o -L/Users/rvalls/.mambaforge/lib -lxml2 -L/Users/rvalls/.mambaforge/lib -lz -L/Users/rvalls/.mambaforge/lib -llzma -lpthread -L/Users/rvalls/.mambaforge/lib -liconv -L/Users/rvalls/.mambaforge/lib -licui18n -licuuc -licudata -lm -L/opt/homebrew/Cellar/r/4.1.2/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
installing to /opt/homebrew/lib/R/4.1/site-library/00LOCK-xml2/00new/xml2/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
Error :  unable to load shared object '/opt/homebrew/lib/R/4.1/site-library/00LOCK-xml2/00new/xml2/libs/xml2.so':
  dlopen(/opt/homebrew/lib/R/4.1/site-library/00LOCK-xml2/00new/xml2/libs/xml2.so, 0x0006): Library not loaded: @rpath/libxml2.2.dylib
  Referenced from: /opt/homebrew/lib/R/4.1/site-library/00LOCK-xml2/00new/xml2/libs/xml2.so
  Reason: tried: '/opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libxml2.2.dylib' (no such file), '/opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libxml2.2.dylib' (no such file), '/opt/homebrew/Cellar/r/4.1.2/lib/R/lib/libxml2.2.dylib' (no such file)
ERROR: installing Rd objects failed for package ‘xml2’
* removing ‘/opt/homebrew/lib/R/4.1/site-library/xml2’

The downloaded source packages are in
	‘/private/var/folders/s8/0tz3dy0d1sbg1_cv0ylkx_m80000gn/T/RtmpsCQBxk/downloaded_packages’
Warning message:
In install.packages("xml2") :
  installation of package ‘xml2’ had non-zero exit status
```

**Comment by brainstorm** [comment]
```
% brew info R
Warning: Treating R as a formula. For the cask, use homebrew/cask/r
R: stable 4.1.2 (bottled)
Software environment for statistical computing
https://www.r-project.org/
/opt/homebrew/Cellar/R/4.1.2 (2,216 files, 64.6MB)
  Poured from bottle on 2021-11-10 at 15:33:18
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/r.rb
License: GPL-2.0-or-later
==> Dependencies
Build: pkg-config ✔
Required: cairo ✔, gcc ✘, gettext ✔, jpeg ✔, libffi ✔, libpng ✔, openblas ✔, pcre2 ✔, readline ✔, tcl-tk ✔, xz ✔
```

**Comment by brainstorm** [comment]
Ok, it turns out that going for the cask version of R all seems to be fine, namely:

```
 $ brew uninstall r
 $ brew install homebrew/cask/r
```

Nevertheless, this PR still stands since libUV is 1 year old now in `r-lib/fs`.

**Comment by colinbrislawn** [comment]
Once this is merged, I can try to get this building on conda-forge: https://github.com/conda-forge/r-fs-feedstock/pull/19

**Comment by gaborcsardi** [comment]
Thanks! I'll do this before the next major release of fs, but I cannot do it from a PR, for security reasons, sorry.

**Comment by brainstorm** [comment]
Sure, reviewing those 146 files must be painful/error prone... how com you don't just use git submodules instead of bundling it all in your repo, @gaborcsardi?

**Comment by gaborcsardi** [comment]
We might need to patch some of the files, and submodules did not work well with some of our tooling, e.g. `remotes::install_github()`.

**Comment by brainstorm** [comment]
The following might sound confrontational but they are not, current mood: agreeable.

> We might need to patch some of the files

Has that happened yet? If it does: Report to upstream (libuv), circumvent by other means through your code, etc...

> submodules did not work well with some of our tooling

Fix that tooling accordingly?

If the comeback argument to my replies is time and resources commitments to fix it, I've nothing else to add, I understand :)

**Comment by gaborcsardi** [comment]
> Has that happened yet? 

Yes.

> If it does: Report to upstream (libuv), circumvent by other means through your code, etc...

These are not necessarily things that make sense in libuv. E.g. libuv used to set up a signal handler, and we had to omit that from fs because it interfered with the signal handler set up by R. Another issue are the pragmas in the libuv code that are not allowed on CRAN, and we need to patch them. Etc.

> Fix that tooling accordingly?

Maybe it is fixed already, IDK, but I also do not care too much.

I have used submodules in another project for a long time, and I hated them. They are also a barrier for contributors. It is better if they do not have to deal with them.

**Pull request closed without merging**
